### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by kennyk65** [awslabs/amazon-ecr-credential-helper#101]
The instruction to run "go get" doesn't work without some prerequisites, would be nice to know what those are.  There is something called GOPATH that has to be set.

The instruction for "make docker" doesn't seem to do anything, so there are apparently some prerequisites there.

Would be nice to have something installable by a package manager of some kind so the user doesn't have to fumble with go.  

Thanks!

**Comment by Torniojaws** [comment]
Definitely. And it doesn't help that ``go get`` fails silently in Ubuntu:
```
$ go get -u github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login
$ docker-credential-ecr-login
docker-credential-ecr-login: command not found
```
No errors or warnings appear after the failed ``go get``.

**Comment by uselvvi** [comment]
This command `go get -u github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login` shows below error. Can you please help how to fix

```
# github.com/awslabs/amazon-ecr-credential-helper/ecr-login/vendor/golang.org/x/sys/unix
../gocode/src/github.com/awslabs/amazon-ecr-credential-helper/ecr-login/vendor/golang.org/x/sys/unix/ioctl.go:18: undefined: runtime.KeepAlive
../gocode/src/github.com/awslabs/amazon-ecr-credential-helper/ecr-login/vendor/golang.org/x/sys/unix/ioctl.go:28: undefined: runtime.KeepAlive
```

**Comment by stedwick** [comment]
I get the same error, doesn't work

**Comment by samuelkarp** [comment]
Hey all, sorry for the delay in responding here.

@kennyk65 The credential helper is now available in several package managers listed in the README file, including Homebrew, Debian Buster, Ubuntu 19.04, Amazon Linux 2, and AUR.  We don't currently have non-packaged binary downloads, but I will update this issue when those become available.

@Torniojaws Thanks for the comment! I'd be happy to merge a contribution updating the instructions in the README if you want to send one.

@uselvvi and @stedwick, what version of Go do you have installed?  The credential helper requires a minimum of Go 1.9 in order to build successfully.

**Comment by stedwick** [comment]
FYI, our organization has decided to go with https://quay.io/ instead, as it so much easier.

**Comment by Torniojaws** [comment]
I created a pull request for the README update:
https://github.com/awslabs/amazon-ecr-credential-helper/pull/167

**Comment by samuelkarp** [comment]
Thanks @Torniojaws for #167; I'm going to resolve this issue as there is now better documentation.  @uselvvi, if you're still having problems feel free to open a new issue.

**Comment by PurityMaina** [comment]
Was this solved for Ubuntu 18?
