### ISSUE TITLE
Authentication required for image to build from

### ISSUE THREAD

**Issue by ajtrichards** [awslabs/amazon-ecr-credential-helper#16]
Our Jenkins install is trying to build a container and we keep getting the following error:

```
13:20:20 Step 1 : FROM *******.dkr.ecr.eu-west-1.amazonaws.com/net.ea.docker.php5:latest
13:20:20 Pulling repository *******.dkr.ecr.eu-west-1.amazonaws.com/net.ea.docker.php5
13:20:21 unauthorized: authentication required
13:20:21 Build step 'Docker Build and Publish' marked build as failure
```

We're using the credential helper to authenticate and it's been working fine. It's only since we changed our base image to a private repository we've had the problem.

**Comment by samuelkarp** [comment]
@ajtrichards Thanks for reporting this.  Docker does not currently parse the `FROM` line in order to request credentials and instead relies on enumerating all possible registries in order to send credentials to the daemon for `docker build`.  There's a work-around here: https://github.com/awslabs/amazon-ecr-credential-helper/issues/9#issuecomment-241184224.

A longer-term approach is to update this helper to use the new functionality merged in https://github.com/docker/docker/pull/26354 for Docker 1.13, though that will still require the helper to track any registry you've used in order to provide the list at build time.

**Comment by ajtrichards** [comment]
Hi @samuelkarp - We already had in place the work around in the #9 comment:

```
{
    "credsStore": "ecr-login",
    "auths": {
	"*******.dkr.ecr.eu-west-1.amazonaws.com": {}
    }
}
```

But still had the error. We made sure this was in place for our ec2-user and root user.

**Comment by s80275** [comment]
Hi @ajtrichards ,
We have the same problem and #9 it worked for me. We run Jenkins with specific OS user, like jenkins.
Did you run Jenkins with ec2-user or not?

**Comment by sentientmonkey** [comment]
FYI, there is a slightly better workaround available after #26 was merged. If you are using Docker 1.13, it will rely on the list command in the credential helper to see what credentials are available. You may need to pull or push the image to add it to the cache file, but once it's there, subsequent builds will work (and refresh properly).

**Comment by sentientmonkey** [comment]
I think now that #26 and #28 have been merged in, FROM should work with your default registry if you are using docker 1.13.0 or newer. This should be a much better work-around than before. Let us know if this works for you!

**Comment by samuelkarp** [comment]
We haven't heard back from you in a while, so I'm closing this issue.  Please let us know if you're still running into difficulties.
