### ISSUE TITLE
docker build will not use ecr-login with credHelpers

### ISSUE THREAD

**Issue by jeffb4** [awslabs/amazon-ecr-credential-helper#173]
This is related I'm sure to many historical issues, but it's currently occurring and it's just different enough I wanted to open a new ticket. In the following `2xxxxxxxxxxx` is the correct account. Credentials are populated into `~/.aws/credentials`. `docker pull` works successfully

```bash
# docker-credential-ecr-login -v
amazon-ecr-credential-helper
Version:    master
Git commit:
# docker --version
Docker version 18.09.7, build 2d0083d
# cat ~/.docker/config.json
{ 
  "credHelpers" : {
    "2xxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com" : "ecr-login"
  },
  "auths" : {
    "2xxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com" : {

    },
    "https://2xxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com" : {

    }
  }
}
# cat Dockerfile.test
FROM 2xxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/node:10

RUN echo test
# echo 2xxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com | docker-credential-ecr-login get
{"ServerURL":"2xxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com","Username":"AWS","Secret":"trimmed"}
# docker -vvv -D build -f Dockerfile.test .
DEBU[0000] Skipping excluded path: .git
Sending build context to Docker daemon  1.185MB
Step 1/2 : FROM 2xxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/node:10
Get https://2xxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/v2/node/manifests/10: no basic auth credentials
# docker pull 2xxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/node:10
10: Pulling from node
8ba884070ff1: Pulling fs layer
```

If instead of `credHelpers` I specify `ecr-login` in `credsStore`, everything works correctly. In the process of debugging I created a "wrapper" ecr-login to get more debugging information

```bash
# cat /usr/local/bin/docker-credential-ecr-login2
#!/bin/sh
NAME=login2
cat > /tmp/repo
echo $* >> /tmp/${NAME}.debug
cat /tmp/repo >> /tmp/${NAME}.debug
resp=$(cat /tmp/repo | docker-credential-ecr-login $1)
echo $resp >> /tmp/${NAME}.debug
echo "===" >> /tmp/${NAME}.debug
echo $resp
exit 0
```

and one thing it reveals is that the credential helper is not being called reliably when specified in `credHelpers`. It is called once (and returns a valid key and still fails the pull for the build) but it is not called on subsequent `docker build`

**Comment by samuelkarp** [comment]
Hey @jeffb4, thanks for reaching out.  Since the problem you're experiencing is with `docker build` not invoking the credential helper reliably rather than with the operation of the credential helper itself, I think it'd be better to open your issue against [the upstream Docker (Moby) repository](https://github.com/moby/moby).

Some more background information in case you are interested in some additional context:

When pushing and pulling images with Docker, the Docker daemon (`dockerd`) doesn't have direct access to credentials.  Instead, the client (like the Docker CLI `docker`) is responsible for sending credential information to the daemon whenever it performs image operations.  This works well with `push` and `pull` operations; the Docker CLI can reliably know which image is being referenced and discover credential information prior to invoking daemon API so it can send it along.

The same constraint applies with `docker build`; the daemon doesn't have access to credentials and relies on the client to send it.  However, the behavior here is a bit more challenging.  When you build an image, you provide a "context" for the build that consists of files and directories that may ultimately be added to your image (through `ADD` and `COPY` directives) as well as the `Dockerfile` itself.  The build API (and `docker build` command) support a variety of ways to provide this "context"; the most typical is a local directory on the filesystem but others like git remotes and URLs are supported.  When you run `docker build`, the CLI is responsible for retrieving the context and streaming it to the daemon.  The complicating factor is that the `Dockerfile` is the only place an image reference is defined, and there's no guarantee that the CLI will receive the appropriate `FROM` line in the `Dockerfile` prior to invoking the API.  Since build is a single API call and all of the parameters are specified up front except for the actual build context, the client is somewhat in a bind for providing credentials.

This requirement means that `docker build` ends up trying to find every credential it can and sends *all* of them to `dockerd` on every build.  When a credential helper is specified as `credsStore`, it does this by invoking `docker-credential-<name> list` to determine which registries are known to the credential helper.  This leads to problems for the Amazon ECR Credential Helper however, since there's no way to indicate every possible ECR registry or every IAM principal that would be used in pulling.  So what the credential helper does today is to keep track of every ECR registry it sees (through `docker pull` and `docker push`) and return all of those when its `list` command is invoked.

I'm not sure what differs between `credsStore` and `credHelpers` in the implementation of `docker build`, but my guess would be something related to being able to enumerate the list of "known" registries.

**Comment by samuelkarp** [comment]
https://github.com/moby/moby/pull/32967 was a discarded pull request that attempted to address this and https://github.com/moby/buildkit/issues/81 appears to be another approach.

**Comment by jeffb4** [comment]
Ugh, I found the problem. And I'm going to commit it to a GH issue in case anyone else has the problem in the future even though it's not a `docker-credential-ecr-login` problem and I look verrrry stupid.

if `credHelpers` contains multiple helpers (as mine does because my paste above is a ~lie~ abbreviated config) they will all be iterated over by `docker build` (see Samuel's explanation of the context). If any handler is missing, say `docker-credential-gcloud` because you haven't gotten around to installing it on your CI runners or test VM, then when https://github.com/docker/docker-ce/blob/ead810e1cf2d6744278c499b1ed4ffc491b7cdbc/components/cli/cli/config/configfile/file.go#L323 hits that error it will abort without an error message.

And you will think the ecr-login helper is exhibiting a failure it isn't.

Sorry for the noise, @samuelkarp

**Comment by samuelkarp** [comment]
@jeffb4 Thanks for updating! It's probably worth opening a bug upstream to Docker/Moby about the silent failure; that looks like a pretty confusing behavior that could be fixed.

**Comment by jeffb4** [comment]
Definitely, https://github.com/docker/cli/issues/1989
