### ISSUE TITLE
Doesn't work with assumed roles

### ISSUE THREAD

**Issue by digitalfiz** [awslabs/amazon-ecr-credential-helper#20]
I can not get this to work using the env var AWS_PROFILE. Maybe the sdk used needs to be updated?

EDIT: This works with a normal profile but it seems to die on a profile that is an assumed role.

**Comment by samuelkarp** [comment]
Normal profiles work, but assumed roles are not quite supported yet.  At a minimum this will require an update to the version of the SDK that is used in this project, but may require additional changes as well.

**Comment by digitalfiz** [comment]
I updated my local copy to the newest SDK, rebuilt it and it still wouldn't work until I also set `AWS_SDK_LOAD_CONFIG=true`. I know you have to do some more testing but it seems to be working just fine with the most updated SDK.

**Comment by samuelkarp** [comment]
If you want to send your update as a pull request (contributing under the terms of the Apache 2.0 license), we can probably take your commit after we've tested it.

**Comment by digitalfiz** [comment]
Coming right up :)

**Comment by samuelkarp** [comment]
Resolved by #21.

**Comment by alasdairnicol** [comment]
@digitalfiz have you got this working using instance profiles on EC2? I can get it to work with assumed roles if I have the access key and secret key in my config file. However I can't get it to work with the instance profile when I remove the keys. I opened this https://github.com/aws/aws-sdk-go/issues/1019 because I think it might be an issue with the SDK, but it might just be a mistake in my `~/.aws` config.
