### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by adrianohrl** [awslabs/amazon-ecr-credential-helper#202]
I did not find any instruction about uninstalling this tool. And I really need to uninstall it in order to make some tests.

How do I do that?

**Comment by samuelkarp** [comment]
Docker will only use this credential helper when configured to do so.  That configuration is typically located in `~/.docker/config.json`; you can remove entries that mention `ecr-login`.

The credential helper also records logs and some cached data in `~/.ecr`.  You can remove that folder if you wish.

To fully uninstall the credential helper (rather than just removing the configuration), you'll need to use the opposite method that you used to install it.  If you installed the credential helper from a package manager (like Homebrew, Yum, Apt, etc) you should use the uninstallation mechanism provided by that package manager.  If you downloaded the compiled binaries from [the "Releases" page](https://github.com/awslabs/amazon-ecr-credential-helper/releases), you can delete the binaries from your system.  If you compiled from source, you can also delete the binaries from your system.
