### ISSUE TITLE
Runtime error when running on a Yocto built OS

### ISSUE THREAD

**Issue by Minipada** [awslabs/amazon-ecr-credential-helper#211]
Hi,
I am trying to run the latest release on a OS created with the [Yocto project](https://www.yoctoproject.org/). This build system is an alternative to buildroot. it is heavily used in the automotive and IoT industry.

I could build the binary, but got runtime issue, it seems to link with the build system folder while it should link to the generated files.

An issue has been created here https://github.com/aws/meta-aws/pull/57 . I don't know anything about go but I checked your compilation flags (CGO_ENABLED = "0" and CGO_LDFLAGS = "-s").
Here are the generated files after the build: [https://brisa-tmp.s3.amazonaws.com/build_amazon-ecr-credential-helper.zip](https://brisa-tmp.s3.amazonaws.com/build_amazon-ecr-credential-helper.zip)

I mention @rpcme, he handles the Yocto repository for all AWS related things at https://github.com/aws/meta-aws.

Please notify me if you need more details or tests/results that I could provide.

**Comment by samuelkarp** [comment]
Hi @Minipada!

My apologies for the delayed response.  I am not very familiar with the Yocto project.  Can you share a bit more information with me, like the architecture you're building for and any non-standard compilation or linker options are being applied to Go projects in Yocto?  I found [this patch](https://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/meta/recipes-devtools/go/go-1.14/0009-ld-replace-glibc-dynamic-linker-with-musl.patch) which seems to imply that in some cases Go may be linked against musl libc instead of glibc; can you tell me which libc you are using?  Are Go packages in Yocto built with `-linkmode=auto` or `-linkmode=external`?  If external, which linker is being used?

I haven't seen the stack trace you provided (https://github.com/aws/meta-aws/pull/57#issuecomment-620144995) before, but it seems to imply that [`ecrPattern` is nil](https://github.com/awslabs/amazon-ecr-credential-helper/blob/v0.4.0/ecr-login/api/client.go#L48).  This variable should only be nil if it [failed compilation here](https://github.com/awslabs/amazon-ecr-credential-helper/blob/v0.4.0/ecr-login/api/client.go#L34), but then [`regexp.MustCompile` should panic itself](https://golang.org/pkg/regexp/#MustCompile).

Thanks!
Sam

**Comment by Minipada** [comment]
Thanks for the answer. Here are some more infos
1. architecture: x86-64
2. i'm using glibc used (git://sourceware.org/git/glibc.git;branch=release/2.29/master)
3. Go is also cross compiled, so here are all the flags used:
```
GO_DYNLINK="1"
GO_EXTLDFLAGS=" -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/YOCTO_DIR/tmp/work/core2-64-poky-linux/amazon-ecr-credential-helper/0.4.0-r0/recipe-sysroot -Wl,-rpath-link=/YOCTO_DIR/tmp/work/core2-64-poky-linux/amazon-ecr-credential-helper/0.4.0-r0/recipe-sysroot/usr/lib/go/pkg/linux_amd64_dynlink -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fstack-protector-strong -Wl,-z,relro,-z,now"
GO_IMPORT="github.com/awslabs/amazon-ecr-credential-helper"
GO_INSTALL="     github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login     github.com/awslabs/amazon-ecr-credential-helper/ecr-login/api     github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cache "
GO_LDFLAGS="-ldflags=\"-r /usr/lib/go/pkg/linux_amd64_dynlink  -extldflags ' -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/YOCTO_DIR/tmp/work/core2-64-poky-linux/amazon-ecr-credential-helper/0.4.0-r0/recipe-sysroot -Wl,-rpath-link=/YOCTO_DIR/tmp/work/core2-64-poky-linux/amazon-ecr-credential-helper/0.4.0-r0/recipe-sysroot/usr/lib/go/pkg/linux_amd64_dynlink -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fstack-protector-strong -Wl,-z,relro,-z,now'\""
GO_LINKMODE=""
GO_LINKSHARED="-linkshared"
GO_PARALLEL_BUILD="-p 4"
GO_RPATH="-r /usr/lib/go/pkg/linux_amd64_dynlink"
GO_RPATH_LINK="-Wl,-rpath-link=/YOCTO_DIR/tmp/work/core2-64-poky-linux/amazon-ecr-credential-helper/0.4.0-r0/recipe-sysroot/usr/lib/go/pkg/linux_amd64_dynlink"
```
It doens't seem to use any external linker, GO_LINKMODE is empty, probably indicating it is using auto. I also cross compiled a hello world application, working fine with same flags. I hope it helps

**Comment by samuelkarp** [comment]
> architecture: x86-64

I know this doesn't satisfy the desire to have it packaged properly in Yocto, but there are statically-linked x86-64 binaries available on the [Releases page](https://github.com/awslabs/amazon-ecr-credential-helper/releases).

>  I also cross compiled a hello world application, working fine with same flags.

Does the cross-compiled hello-world application use the `regexp.MustCompile` function?  I wonder if something is specifically weird about that package.

> GO_LINKSHARED="-linkshared"

> 	-linkshared - build code that will be linked against shared libraries previously created with -buildmode=shared.

I'm wondering if the `regexp` package isn't available in your build of the Go standard library?

**Comment by samuelkarp** [comment]
Hi @Minipada! I haven't heard back from you in a while, so I'm going to close this issue. Please feel free to re-open it or to open a new issue if you have any further questions.

**Comment by Minipada** [comment]
Hi @samuelkarp unfortunately I didn't find the opportunity to dig more into it. I'll ping if needed. Thank you
