### ISSUE TITLE
Using mfa_serial causes failure to authenticate when MFA code is required

### ISSUE THREAD

**Issue by pjroth** [awslabs/amazon-ecr-credential-helper#216]
I have mfa_serial configured as well as `credential_process = aws-vault exec default --json --prompt=terminal` in my `~/.aws/config` I get the following errors when running this command:

`# AWS_SDK_LOAD_CONFIG=true docker pull 496076859928.dkr.ecr.us-east-1.amazonaws.com/my-service:1.0.0
Enter token for arn:aws:iam::496076859928:mfa/myusername: Enter token for arn:aws:iam::496076859928:mfa/myusername: Error response from daemon: Get https://496076859928.dkr.ecr.us-east-1.amazonaws.com/my-service:1.0.0: no basic auth credentials
`

The output does NOT pause for mfa token though you can see above it did output the prompt.

Logs (`~/.ecr/log/ecr-login.log`):

`time="2020-06-04T13:08:51-04:00" level=debug msg="Could not fetch credentials for cache prefix, disabling cache" error="ProcessProviderExecutionError: error in credential_process\ncaused by: exit status 1"
time="2020-06-04T13:08:51-04:00" level=debug msg="Retrieving credentials" region=us-east-1 registry=496076857328 serverURL=496076859928.dkr.ecr.us-east-1.amazonaws.com
time="2020-06-04T13:08:51-04:00" level=debug msg="Calling ECR.GetAuthorizationToken" registry=496076859928
time="2020-06-04T13:08:51-04:00" level=error msg="Error retrieving credentials" error="ecr: Failed to get authorization token: ProcessProviderExecutionError: error in credential_process\ncaused by: exit status 1"`

Since I'm using aws-vault (which stores mfa sessions) if I already have an MFA session in aws-vault (from previous command that shares this mfa/creds) then the above docker command works successfully.  This suggests to me it's just the prompt for MFA (where it doesn't seem to wait for my input) is the problem.

**Comment by pjroth** [comment]
It is possible this is related to #180 although the log messages in that issue don't look the same is what I see.

**Comment by samuelkarp** [comment]
`credential_process` is supported, but interactive credential processes (like `aws-valut --prompt=terminal`) are not.  Like https://github.com/awslabs/amazon-ecr-credential-helper/issues/180#issuecomment-549943135, the credential helper doesn't have a way to prompt for input itself or to delegate that ability out.

I don't anticipate a way to add this ability unless the Docker credential helper protocol changes.

I'm going to close this in favor of #180 even though it's not precisely the same thing because the core problem of prompting is still common to both.
