### ISSUE TITLE
[Feature Request] Add Support for Public ECR

### ISSUE THREAD

**Issue by PatrickXYS** [awslabs/amazon-ecr-credential-helper#248]
Given we have launched [Public ECR registry](https://aws.amazon.com/blogs/aws/new-amazon-ec2-g4ad-instances-featuring-amd-gpus-for-graphics-workloads/?nc1=b_nrp) last week, we should expect huge volume of feature-requests for using amazon-ecr-credential-helper with public ecr support added.

We're experimenting POC for CD pipeline by using amazon-ecr-credential-helper, and expect to massively use public ECR.

I can bring up a design doc and implement Public ECR alongside with existing Private ECR implementation.

**Comment by PatrickXYS** [comment]
/cc @samuelkarp @kzys 

Appreciate any insights from you!

**Comment by Jeffwan** [comment]
Seems ecr internally doesn't handle public registry. Instead, a separate API is used. 

https://docs.aws.amazon.com/sdk-for-go/api/service/ecrpublic/

To give the best user experience, I think it's great to support public ecr in this credential helper as well rather than creating separate one. It should determine the api to use based on the registry patterns internally and hide as many details as it can. 

- public: `public.ecr.aws/h4kxxxxx`
- private: `692xxxxxxx.dkr.ecr.us-east-1.amazonaws.com`

**Comment by jahkeup** [comment]
Thanks for bringing this up! 

> Seems ecr internally doesn't handle public registry. Instead, a separate API is used.

You're exactly right, this means the credential helper will need to be refactored a bit to handle both ECR refs and ECR Public refs in order to provide the correct set of credentials to Docker. Today, the credential helper assumes that it either is or isn't responsible for ECR refs only and has a single factory that is configured based on the ref.

**Comment by johnnyshields** [comment]
AWS team, this is a huge issue. I'm flabbergasted that ECR Public was launched without this. We switched all our builds from DockerHub to ECR Public only to be in a worse situation re: rate limiting. Builds are broken everywhere 🔥🔥🔥 

Please make sure cross-region support is included in this; we are hosting in `ap-northeast-1`

**Comment by vivekpd15** [comment]
+1
