### ISSUE TITLE
Please provide installation instructions for Ubuntu 18.04

### ISSUE THREAD

**Issue by ZillaG** [awslabs/amazon-ecr-credential-helper#257]
I tried installing this on 18.04, and `makepkg` wasn't found. From what I understand, that's installed by `packman` so I cloned  that, but its installation instructions says to run `./autogen.sh` but that's nowhere to be found in the cloned files.

**Comment by samuelkarp** [comment]
Hi @ZillaG, it sounds like you're attempting to follow instructions for Arch Linux rather than Ubuntu.  The credential helper is not present in the Ubuntu 18.04 repositories, but you can [download binary releases here](https://github.com/awslabs/amazon-ecr-credential-helper/releases).

The request for Ubuntu 18.04 is tracked in https://github.com/awslabs/amazon-ecr-credential-helper/issues/235 so I'm closing this as a duplicate.

**Comment by samuelkarp** [comment]
https://github.com/awslabs/amazon-ecr-credential-helper/issues/188 is an older issue tracking the same thing.
