### ISSUE TITLE
Deprecating for email flag. Will this affect amazon-ecr-credential-helper?

### ISSUE THREAD

**Issue by daviddyball** [awslabs/amazon-ecr-credential-helper#36]
Just got an email from the AWS team warning of incompatibilities with `awscli`'s `ecr get-login` command and the upcoming `docker` 17.06 version that will deprecate the `--email` flag originally part of `docker login`.

Will this have a knock-on affect to this project?

**Comment by samuelkarp** [comment]
The credential helper should not be affected by this change, but please let us know if you run into any problems.

**Comment by colin-mcdonald** [comment]
This is causing issues for me...basically `aws ecr get-login` returns a docker-login command that has `-e none` flag set (which is the shorthand for --email).  Because of this I manually have to delete the `-e none` each time to run it.

I also see a new warning when I execute the command returned from `aws ecr get-login` which does not prevent execution:
WARNING! Using --password via the CLI is insecure. Use --password-stdin.

**Comment by samuelkarp** [comment]
@colin-mcdonald Please file issues with the AWS CLI against the [AWS CLI GitHub repo](https://github.com/aws/aws-cli/).

**Comment by rpnguyen** [comment]
@colin-mcdonald You'll need to call `aws ecr get-login --no-include-email`. See this [forum post](https://forums.aws.amazon.com/ann.jspa?annID=4656) for more context
