### ISSUE TITLE
Release version inconsistent with docker-credential-ecr-login version

### ISSUE THREAD

**Issue by tnaroska** [awslabs/amazon-ecr-credential-helper#432]
Artifacts of github release 0.6.0 report different version when executed with `docker-credential-ecr-login version`.
To reproduce:
```
curl -O https://amazon-ecr-credential-helper-releases.s3.us-east-2.amazonaws.com/0.6.0/darwin-amd64/docker-credential-ecr-login
chmod +x docker-credential-ecr-login
./docker-credential-ecr-login version
0.6.3
```
Same discrepancy observed with linux binaries. Artifact from github release 0.6.0 reports as version 0.6.3.

**Comment by jowand-barracuda** [comment]
I've noticed this too--it makes automation difficult since I want to check to make sure a particular version is installed, and the version is part of the binary release url:

`https://amazon-ecr-credential-helper-releases.s3.us-east-2.amazonaws.com/{{ aws_ecr_cred_helper_bin_version }}/linux-amd64/docker-credential-ecr-login` 

so I can't use the same variable to check the version and download the packages if it's not installed.

**Comment by pbanka-17** [comment]
Not only this, the previous versions seem to contain binary with version 0.6.3. 
Try downloading the artifact from release [v0.5.0](https://github.com/awslabs/amazon-ecr-credential-helper/releases/tag/v0.5.0)

**Comment by tnaroska** [comment]
still broken in release 0.7.0. now reporting:
```
./docker-credential-ecr-login version
 (github.com/docker/docker-credential-helpers) v0.0.0+unknown
```
