### ISSUE TITLE
unknown shorthand flag: 'e' in -e

### ISSUE THREAD

**Issue by ssolari** [awslabs/amazon-ecr-credential-helper#51]
Problem
======

This problem seems to have suddenly emerged. 

When running ecr-login with a profile:

`aws ecr --profile myprofile get-login`

The return string is:

`docker login -u AWS -p <long_key> -e none https://<account>.dkr.ecr.us-west-2.amazonaws.com`

However, copying and pasting this return string results in the error:

`unknown shorthand flag: 'e' in -e`

Removing the `-e none` from the returned string performs login as usual.

Desired behavior
============

The returned string delivered by the cli should probably return something that works with copy and paste.

**Comment by danielcompton** [comment]
@ssolari this repo is for the Docker ECR credential helper, not the AWS CLI. If you want to use the `aws` command, then you need to specify `--no-include-email`:

```console
$ aws ecr get-login help
...
       --include-email | --no-include-email (boolean) Specify if the '-e' flag
       should  be  included in the 'docker login' command. The '-e' option has
       been deprecated and is removed in docker version 17.06 and  later.  You
       must specify --no-include-email if you're using docker version 17.06 or
       later. The default behavior is to include the '-e' flag in the  'docker
       login' output.
```

**Comment by samuelkarp** [comment]
@ssolari, @danielcompton is correct that this repository is for the Amazon ECR credential helper, which is different from the AWS CLI.  This issue was discussed on https://github.com/aws/aws-cli/issues/1926 and resolved by https://github.com/aws/aws-cli/pull/2619.  You'll want to update your installed copy of the CLI to at least [version 1.11.91](https://github.com/aws/aws-cli/commit/ca919c5b634228076766f1458680d9dd850ad621) in order to use the new `--no-include-email` flag.

**Comment by acooley** [comment]
It might have been good to address this a little faster. Currently the latest stable version of docker-ce and the latest 'stable' version of awscli don't work together. I'd blame docker-ce but they have been warning about the depreciation.

**Comment by samuelkarp** [comment]
Locking this issue; please see my previous comment.
