### ISSUE TITLE
Work with helm registry login?

### ISSUE THREAD

**Issue by vintq** [awslabs/amazon-ecr-credential-helper#664]
I have an ECR repo that stores helm charts for EKS but was wondering if it would be possible to make the credential helper work with helm registry?

Currently I run `aws ecr get-login-password --region us-west-1 --profile=user | HELM_EXPERIMENTAL_OCI=1 helm registry login --username AWS --password-stdin 012345678910.dkr.ecr.us-west-1.amazonaws.com`

**Comment by MartinEmrich** [comment]
https://github.com/helm/helm/issues/10312 states somewhere, that it should work. And It worked for me for a long time.

But lately I switched from docker to podman, and uninstalled docker. Since then it no longer works. Helm seems to read the still-existing docker config and execute the docker-credential-ecr-login helper executable, but that in turn seems to require an actual docker installation present.

**Comment by austinvazquez** [comment]
Thanks @MartinEmrich for the tip. I'm not familiar with the helm client but cool to see the credential helper being useful in other spaces.

**Comment by johnc1996** [comment]
Hey @MartinEmrich can you provide exactly what your `~/.docker/config.json` looks like to achieve what OP was asking? I always have to manually run the command OP posted

**Comment by MartinEmrich** [comment]
The simplest variant would be
````
{
  "credHelpers": {
    "<accountid>.dkr.ecr.<region>.amazonaws.com": "ecr-login",
    "<accountid>.dkr.ecr.<region>.amazonaws.com": "ecr-login",
	....
  },
  "credsStore": "ecr-login"
}
````

**Comment by johnc1996** [comment]
Actually scratch that, the whole point was wanting to be able to pull charts from helm automatically using the ecr credential helper the same as it does for docker. So are you saying @MartinEmrich that you have that config and you then don't have to explictly have to do a `helm registry login` command when you've got that config?
